### ISSUE TITLE
Invite for collaboration

### ISSUE THREAD

**Issue by nganhkhoa** [bluesadi/OLLVM-plusplus#2]
Hi bluesadi or 34r7hm4n ,

First of, I would like to thank you for your hardwork researching obfuscation methods with LLVM, or OLLVM as we all call. I have checked out your blog posts and projects, those are wonderful and insightful.

As I am currently working on OLLVM and researching about obfuscation. I think that we can work together to bring more ideas and improve the project. That is why I am writing you this as an invitation for collaboration.

Furthur details can be discussed directly to me in discord: `luibo#0645`.

If you're reluctant to have a conversation, you can try our RE challenge released at https://ctf.hackemall.live/. The CTF starts 00:00 01/01/2022 (UTC). The challenge is named `crackme pls` and authored by `midas` and `luibo`. The challenge is obfuscated using our customed version of OLLVM.

Looking forward to your reply.

P/S 1: I left comments in your latest blog post about MBA, but I feel the need to message you here because there is no direct contact methods and you may not read blog comments and the CTF is starting soon.

P/S 2: I welcome your CTF team to join the CTF also.

P/S 3: Have a wonderful new year.

**Comment by bluesadi** [comment]
Thanks for your invitation!
